curl 'https://api.spacetraders.io/v2/systems/X1-UF75' \
 --header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWVyIjoiQUxFWEoiLCJ2ZXJzaW9uIjoidjIuMS40IiwicmVzZXRfZGF0ZSI6IjIwMjMtMTItMzAiLCJpYXQiOjE3MDQyMDkxMzksInN1YiI6ImFnZW50LXRva2VuIn0.PvyK2ybQtMftKG_wDwozCCgxvnGWHy1_BSc7LSF_Y87C9v2ewN0nYu87OZ77DZPcfE-2Gw_GkAPakgCMHKdbbXj7QMl_QqetY8x3c0PzKHV6OCW9v-UXrw_s-fI8aeZpLpQW9OdPrq7MsZecyD1hhP4c8bwMvJbqChQqiTGfKQrpG4ftot53EfYvNPetb9y5iz0OgY6sqkG_ielzu6jLAyde_MxsQIimLewexSUcr9Etg85s9dZUk4EGSYtvG3D4ZZSjN75r6HUX2w1DKCugSc-t78SfkFt7OeDpar7k0BvbaQQw3DZWQdCoJw-HhJem-6ZEkDgdPR6XhryE0IHfZA'